name: Test Sync Diagnostic

on:
  workflow_dispatch:

jobs:
  diagnostic:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Initial Check
      run: |
        echo "🔍 DIAGNÓSTICO DE SINCRONIZAÇÃO"
        echo "================================"
        echo "Data/Hora: $(date)"
        echo "Runner: ${{ runner.os }} - ${{ runner.arch }}"
        echo "Evento: ${{ github.event_name }}"
        
    - name: Check Secrets Configuration
      run: |
        echo "📋 Verificando Secrets..."
        echo "========================="
        
        # Verificar se os secrets existem (não mostra o valor)
        if [ -z "${{ secrets.GOOGLE_CLIENT_ID }}" ]; then
          echo "❌ GOOGLE_CLIENT_ID não configurado!"
        else
          echo "✅ GOOGLE_CLIENT_ID configurado (${#GOOGLE_CLIENT_ID} caracteres)"
        fi
        
        if [ -z "${{ secrets.GOOGLE_CLIENT_SECRET }}" ]; then
          echo "❌ GOOGLE_CLIENT_SECRET não configurado!"
        else
          echo "✅ GOOGLE_CLIENT_SECRET configurado"
        fi
        
        if [ -z "${{ secrets.GOOGLE_REFRESH_TOKEN }}" ]; then
          echo "❌ GOOGLE_REFRESH_TOKEN não configurado!"
        else
          echo "✅ GOOGLE_REFRESH_TOKEN configurado"
        fi
        
        if [ -z "${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}" ]; then
          echo "❌ GOOGLE_DRIVE_FOLDER_ID não configurado!"
        else
          echo "✅ GOOGLE_DRIVE_FOLDER_ID configurado"
        fi
        
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        
    - name: Check Repository Structure
      run: |
        echo "📁 Estrutura do Repositório:"
        echo "============================"
        echo "Total de arquivos: $(find . -type f | wc -l)"
        echo "Total de pastas: $(find . -type d | wc -l)"
        echo "Tamanho total: $(du -sh . | cut -f1)"
        echo ""
        echo "Pastas principais:"
        ls -la
        echo ""
        if [ -d "Certificados" ]; then
          echo "📂 Pasta Certificados encontrada!"
          echo "Arquivos em Certificados: $(find Certificados -type f | wc -l)"
        else
          echo "❌ Pasta Certificados não encontrada no repositório"
        fi
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Test Google Drive Connection
      run: |
        pip install google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2 requests
        
        python << 'EOF'
        import os
        import sys
        import json
        import requests
        from googleapiclient.discovery import build
        from google.oauth2.credentials import Credentials
        
        print("\n🔌 Testando Conexão com Google Drive")
        print("=====================================")
        
        # Verificar variáveis
        client_id = '${{ secrets.GOOGLE_CLIENT_ID }}'
        client_secret = '${{ secrets.GOOGLE_CLIENT_SECRET }}'
        refresh_token = '${{ secrets.GOOGLE_REFRESH_TOKEN }}'
        folder_id = '${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}'
        
        if not all([client_id, client_secret, refresh_token, folder_id]):
            print("❌ Secrets não configurados corretamente!")
            sys.exit(1)
        
        print("✅ Todos os secrets estão presentes")
        
        # Testar renovação de token
        print("\n🔄 Testando renovação de token...")
        token_url = "https://oauth2.googleapis.com/token"
        token_data = {
            'client_id': client_id,
            'client_secret': client_secret,
            'refresh_token': refresh_token,
            'grant_type': 'refresh_token'
        }
        
        response = requests.post(token_url, data=token_data)
        print(f"Status da resposta: {response.status_code}")
        
        if response.status_code != 200:
            print(f"❌ Erro ao renovar token: {response.text}")
            sys.exit(1)
        
        access_token = response.json().get('access_token')
        if not access_token:
            print("❌ Token de acesso não recebido!")
            sys.exit(1)
            
        print("✅ Token renovado com sucesso!")
        
        # Testar conexão com Drive
        print("\n☁️ Testando API do Google Drive...")
        try:
            credentials = Credentials(
                token=access_token,
                refresh_token=refresh_token,
                token_uri="https://oauth2.googleapis.com/token",
                client_id=client_id,
                client_secret=client_secret,
                scopes=['https://www.googleapis.com/auth/drive']
            )
            
            service = build('drive', 'v3', credentials=credentials)
            
            # Verificar informações da conta
            about = service.about().get(fields='user').execute()
            user_email = about.get('user', {}).get('emailAddress', 'Desconhecido')
            print(f"✅ Conectado como: {user_email}")
            
            # Verificar pasta
            print(f"\n📁 Verificando pasta ID: {folder_id}")
            try:
                folder_info = service.files().get(fileId=folder_id).execute()
                print(f"✅ Pasta encontrada: {folder_info.get('name')}")
                
                # Verificar pasta do repositório
                query = f"name='Gad_Pesquisa' and '{folder_id}' in parents and mimeType='application/vnd.google-apps.folder' and trashed=false"
                results = service.files().list(q=query, fields='files(id, name)', pageSize=1).execute()
                
                if results.get('files'):
                    repo_folder_id = results['files'][0]['id']
                    print(f"✅ Pasta do repositório encontrada: Gad_Pesquisa (ID: {repo_folder_id})")
                    
                    # Contar arquivos
                    print("\n📊 Analisando conteúdo...")
                    all_query = f"'{repo_folder_id}' in parents and trashed=false"
                    all_results = service.files().list(
                        q=all_query,
                        fields='files(name, mimeType)',
                        pageSize=1000
                    ).execute()
                    
                    files = all_results.get('files', [])
                    folders = [f for f in files if f['mimeType'] == 'application/vnd.google-apps.folder']
                    regular_files = [f for f in files if f['mimeType'] != 'application/vnd.google-apps.folder']
                    
                    print(f"  📁 Subpastas: {len(folders)}")
                    print(f"  📄 Arquivos: {len(regular_files)}")
                    
                    # Verificar pasta Certificados
                    cert_folder = next((f for f in folders if f['name'] == 'Certificados'), None)
                    if cert_folder:
                        print(f"\n✅ Pasta 'Certificados' encontrada no Drive!")
                        
                        # Contar arquivos na pasta Certificados
                        cert_query = f"'{cert_folder['id']}' in parents and trashed=false"
                        cert_results = service.files().list(
                            q=cert_query,
                            fields='nextPageToken, files(id)',
                            pageSize=1000
                        ).execute()
                        
                        cert_count = len(cert_results.get('files', []))
                        has_more = cert_results.get('nextPageToken') is not None
                        
                        print(f"  📄 Arquivos em Certificados: {cert_count}{'+ (tem mais páginas)' if has_more else ''}")
                    else:
                        print("\n⚠️ Pasta 'Certificados' não encontrada no Drive")
                        print("  Pastas disponíveis:", [f['name'] for f in folders])
                else:
                    print("❌ Pasta do repositório 'Gad_Pesquisa' não encontrada no Drive")
                    
            except Exception as e:
                print(f"❌ Erro ao acessar pasta: {e}")
                
        except Exception as e:
            print(f"❌ Erro na conexão com Drive: {e}")
            import traceback
            traceback.print_exc()
            
        print("\n✅ Teste de conexão concluído!")
        EOF
